- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker inspect --format '{{ '{{' }} .NetworkSettings.IPAddress {{ '}}' }}' instance1" #"sudo docker service ls --format '{{'json . '}}' | jq --slurp"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
