- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: sudo docker service ls --format "{{json . }}"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
