- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format '{{ '{{' }} json . {{ '}}' }}' > /tmp/services.json"

     
    - copy: src= /tmp/services.json dest=services.json

    - include_vars:
        file: services.json
        name: services
      
      
      
    - debug:
        var: services
           
      
