---
- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: 
        src: list_docker_services.py 
        dest: /tmp/list_docker_services.py 
        mode: 077
        
    - shell: python  /tmp/list_docker_services.py  > /tmp/services.json 
    
    - copy: 
        src: get_service_urls.py
        dest: /tmp/get_service_urls.py
        mode: 077

    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10
      
    - shell: python /tmp/get_service_urls.py /tmp/services.json "{{public_ip['json']['ip']}}"  > /tmp/service_urls.json 
      
    - debug:
        var: out
        
    - fetch:
        src: /tmp/service_urls.json 
        dest: /var/lib/awx/service_urls.json 
        flat: yes 
        
        
    
- hosts: swarm_manager_prime
#   connection: local
  vars:
    service_urls: "{{  lookup('file', '/var/lib/awx/service_urls.json') | from_json }}"
  tasks:  
  

    - set_fact: 
        service_urls: "{{service_urls}}"    

    - set_stats:
        data: 
          tic:
            attributes: 
              service_urls: "{{service_urls}}"   
      register: attributes
