- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format '{{ '{{' }} json . {{ '}}' }}' > /tmp/services.json"


    - include_vars:
        file: /tmp/services.json
        name: services
        remote_src: yes
      
      
      
    - debug:
        var: services
           
      
