- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format '{{ '{{' }} .NetworkSettings.IPAddress {{ '}}' }}' | jq --slurp"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
