- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker ps --format '{{ '{{' }} .Names {{ '}}' }}'"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
