---
- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: 
        src: list_docker_services.py 
        dest: /tmp/list_docker_services.py 
        mode: 077
    
    - shell: python /tmp/list_docker_services.py > /tmp/services.json 
    
    - fetch:
        src: /tmp/services.json 
        dest: /tmp/
        flat: yes 
    
#     - include_vars:
#         file: ./services.json 
#         name: services
      
#     - debug:
#         var: item
#       loop: "{{ services.stdout | dict2items }}"
        
#     - name: Get the public IP address of the network.
#       uri:
#         url: https://api.ipify.org?format=json
#         method: Get
#       changed_when: false
#       register: public_ip
#       until: public_ip.status == 200
#       retries: 6
#       delay: 10
#     - set_fact: 
#         attributes: 
#           service_urls: {{public_ip['ip']}}:{{ 
#       loop: "{{ services.stdout | dict2items }}"

#     - set_stats:
#         data: "{{ attributes }}"
#       register: attributes
- hosts: localhost
  connection: local
  tasks:  
 
    - shell: ls -lah /tmp
      
