- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - name: Get info on Docker Swarm
      docker_swarm_info:
        services: yes
      ignore_errors: yes
      register: result
      
      
    - debug:
        var: result
           
      
