- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format '{{ '{{' }} json . {{ '}}' }}' > /tmp/services.json"
      
    - shell: "cat /tmp/services.json | jq --slurp"
      register: services
      
      
      
    - debug:
        var: services.stdout
           
      
