---
- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: 
        src: list_docker_services.py 
        dest: /tmp/list_docker_services.py 
        mode: 077
        
    - shell: python  /tmp/list_docker_services.py  > /tmp/services.json 
    
    - copy: 
        src: get_service_urls.py.py 
        dest: /tmp/get_service_urls.py.py 
        mode: 077

    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10
      
    - shell: python /tmp/get_service_urls.py /tmp/services.json "{{public_ip}}"
        
#     - fetch:
#         src: /tmp/services.json 
#         dest: /var/lib/awx/services.json 
#         flat: yes 
        
        
    
- hosts: swarm_manager_prime
#   connection: local
  vars:
    services: "{{  lookup('file', '/var/lib/awx/services.json') | from_json }}"
  tasks:  
  

    - copy: 
        src: list_docker_services.py 
        dest: /tmp/list_docker_services.py 
        mode: 077
        
        
  
    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10

    - set_fact: 
        attributes: 
          service_urls: "{{item}}"
      loop: "{{ services }}"

#     - set_stats:
#         data: "{{ attributes }}"
#       register: attributes        
        
    - debug:
        var: attributes
      
