- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: src=list_docker_services.py dest=/tmp/list_docker_services.py mode=077
    
    - script: /tmp/list_docker_services.py
      register: services      
      
    - debug:
        var: services
           
      
