- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: src=clean_json.py dest=/tmp/clean_json.py mode=077
    
    - shell: python /tmp/clean_json.py /tmp/services.json /tmp/services_clean.json
      register: services      
      
    - debug:
        var: services
           
      
