- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: src=get_swarm_services.sh dest=/tmp/get_swarm_services.sh mode=077
    
    - local_action: command sh /tmp/get_swarm_services.sh
      register: services      
      
    - debug:
        var: services
           
      
