---
- hosts: swarm_manager_prime
  become: yes
  tasks:
    
         
    - copy: 
        src: list_docker_services.py 
        dest: /tmp/list_docker_services.py 
        mode: 077
    
    - shell: python  /tmp/list_docker_services.py  > /tmp/services.json 
    
    - shell: jq . /tmp/services.json 
    
    - fetch:
        src: /tmp/services.json 
        dest: /var/lib/awx/services.json 
        flat: yes 
    

      

        
#     - name: Get the public IP address of the network.
#       uri:
#         url: https://api.ipify.org?format=json
#         method: Get
#       changed_when: false
#       register: public_ip
#       until: public_ip.status == 200
#       retries: 6
#       delay: 10
#     - set_fact: 
#         attributes: 
#           service_urls: {{public_ip['ip']}}:{{ 
#       loop: "{{ services.stdout | dict2items }}"

#     - set_stats:
#         data: "{{ attributes }}"
#       register: attributes
- hosts: localhost
  connection: local
  vars:
    services: "{{  lookup('file', '/var/lib/awx/services.json') | from_json }}"
  tasks:  
        
#     - include_vars:
#         file: /var/lib/awx/services.json 
#         name: services
        
        
    - debug:
        var: services
      
