- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format '{{ '{{' }} json . {{ '}}' }}' > services.json && cat services.json | jq --slurp"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
