- hosts: swarm_manager_prime
  become: yes
  tasks:
    
    - shell: "sudo docker service ls --format  {% raw %}'{{ .NetworkSettings.IPAddress }}' {% endraw %}"
      register: services
      
      
    - debug:
        var: services.stdout
           
      
